sudo: false
os:
- linux
- osx
addons:
  apt:
    packages:
    - clang
install:
- export CXX="clang++"
- npm install yarn --global
- yarn install
language: node_js
node_js:
- '6'
script:
- yarn run rebuildNative
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script: node bin/deploy-travis.js
  on:
    repo: CircuitCoder/Console-Lite
    all_branches: true
    node: '6'
env:
  global:
  - secure: "RhVmrhuQwzZzdHBH5qogtEijFVtSARPOqY9o8a7K4MCi19OOhyGTWPgjWistecQIeDcFZtt6GFEWPR+NEcvJJABcZYGaxdisM+Cuh65GDBXW8EU8HHlZ9pkME+1K0y1hicyzi/v5W4GriAXFDBZCIDxISTFvJYSwlYbRlksI+zTNJpwovmxtD3oeGzdqDz2Jgty80e5LsAtoDBbwQQWypJMq+SYjt8WyBn53DfnSg8z8GbX1BVqs9W6BcdO5V6WvnuSU0E61GCwFsu6dYPKzsms39FJk271Q6pSleqkSdyT0FRZkVUURBcEC6ucNe6//5DdozbzethidcqcvsxM3Z+bjkTUk+bmPg2Av0m02xlEVQydwoxs4Xf1H2vSMwvhNRSJ8qDHKAADFmmdDTvc8q+2Isoao7ZesmwfkVC8RQNjS0Mx84wnDNvqt+M1PbVdyAeKNDjZDABbkS8BufSlCo0N0tyTV/bCE55WDJaSJ+LPDF27s04AbVCBRwkjZBDF6CT2EQqoOBq3RP3EhMaSXfpyYhK2wIx9cbxVOjI/AjijyG0rIoEaUKY1HqCV+nMBUQdAZw8QmP9Yrj51zTpLeY7iYek1VNNJmOWZgqiu1N8f6Aw2YqCadNIJqVGUDWPdsaCy/GZRg4F1j9VB5ZA2cROUYG6kd20n5AKlRjPumpJA="
  - secure: "OEcRx/OCv1aA73m4rcuJ/cOu61/INr830H/9MZ3W7mn7B/jyBY3zc0g4b90C/P24z+vZKdeeBn9mCIQKlb2Z1n8tkittYCLi3dMy/WTVEFTFNV2nQc05FJwZL8nOvYCWvAChT+EtF/RU0mbIEoeWq5sUCdWza306gAjOlmLWKo225K3MvdwuiAFesdb3lJWTlZ0m8Ccoy+gwqsXa18KazAFLyD22WPK51f6pDjJ30lEdV4qzVU8eaZy4egkJVbgaL8ikvFhgAhNSsYqngu7CBTtO1XvidO5G2Z4XJ2oArfWL5b0o1MXk+BMRqqekJY3lytqYx3jE45AnYVG8/5xnhJFkbPv5Pwzp0/qMuwAZC9gbV1LX+pT/Omd6GbZwXgQqFu/oNMd+5BNqnz8nzlFXcWUa6pRjKvUENLLz66bw/mDe41HV/dM+4OFPQtaJbjwSSBx4j8GRJ2+rCNnsjMmk65pIVo2YNmwZC39xXCSOboUpK0Vz+L+CDBjWU2kxv1qJju8DU+nMhuFj1IMYx9Mgm/GimLFw2szZMxq+LxTusFr/rm0xPowtUVFtflRMTX6qQ7NVXor/6JqrLKYAhasJAc0MLizQkOxsjkECt8Ik5V0ClmdggVrXD72drNu7QKRMHBehRu6/1UZDSNM2VNL9lmbqQJyDG5d1j/yayUoKuUw="
