sudo: false
os:
- linux
- osx
addons:
  apt:
    packages:
    - clang
install:
- export CXX="clang++"
- npm install yarn --global
- yarn install --frozen-lockfile
language: node_js
node_js:
- '10'
script:
- yarn run rebuildNative
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script: node bin/deploy-travis.js
  on:
    repo: CircuitCoder/Console-Lite
    all_branches: true
    node: '10'
