sudo: false
os:
- linux
- osx
addons:
  apt:
    packages:
    - clang
install:
- export CXX="clang++"
- npm install yarn --global
- yarn install --frozen-lockfile --network-concurrency 1
language: node_js
node_js:
- '10'
script:
- yarn run rebuildNative
- yarn test
deploy:
- provider: script
  skip_cleanup: true
  script: node bin/deploy-travis.js
  on:
    repo: CircuitCoder/Console-Lite
    all_branches: true
    node: '6'
env:
  global:
    - secure: "OSjU4VxRmQFh/PNf9soSqxQ1gEk3Zb0KBSF9C0Xqy1cCD+bEklF9lEOrVPfUrMCKaa3TMsm9aTUoRymj1oYByo5msnG3s3AYCjuJ/NXM03rUTb9QfrlxZglAQsiFZgMpQEhijgF4o3EPAKqgcmHJsCj8ndpC6FRaSIap9Si7uAZAkpM1FUdL1vJ0pg4mXZsAhigLUXpfqOgvY/b4ryYBl24EOCw1ZYnE37bUawX13K43+O+rZkVygG3GlA/8OlbFLh96GoDscB9ho/zTXNMsjJ1gTr0IGR5qkdxo4IV7cBc/DZqiRWam17iF/uXA4qyKglTGYnkiXnPO/Zpul1VqP56xAIT1Q0V9hxJPDzSzuiSLzu3dYVwChQwD9e7EszlvZZSkT89OGAgSMm8FRqB8+bdMF/ZLm93Qfh5Ty4Eyulqypn/6M/BGqwzyes+YwQHWswPAX83YNzCrzali2vwc1XXeS4Gn2HuXvtjtxcfGST/Y+qaOEhEmQrP42wgtszF9kzxnNf0MSPWBFpfjCiBx0j55Kw5NpnO2l76WA9vM2q5ItB6nZEyHmdddj8LroPj8Ax4voViFQlqBjIMSRIun0yEd4JzwqGDFk7HEuSaW7IButETFu+Am4see1YLrcJ6lIIXGpQEQ2TT9WFYcklc55EafvTVfGJgzPh1nsDU/UN8="
    - secure: "FTu4qJpP+2NC7j/RgwgKF45/g9muVakSTfF9oqbkj4UhdU8FTXqev1w88M/1IQRne9WBlscvDYF7IMH9VSomUVxKYE9irq4oh5iLpllhbK5Kz74oZmsO6wmWUeF7nAY2rLIrteAj302ORvHpUujFI6oga9SJG/CofVYM6Gu6PAdYRAB4eRizRnza8hsWWy6e62j+Gm7yfE+YmTqE9fgH6lCjFax/lKDT32O+ujMGpMzMix2fBgyRx1TkuN0D5k8UHgavTFuQgt5zPW3Hbm/CxVp2xfwcf1XywnZ4wlv8GwOPDRabC1zfxRSVWjrzmD47dI6MUG7r94oWsqQ/TlWpLbsfmldERYss9B27O+SA6QhGdvQmX7f0p14PK2sMoSj0CEgaAog/jKi5R7mBcOPkXDj6Gi86aflCuxNNNP0msTa3nah8tRzzpqPCQxuYFogBYymuLOgbBDy1zGrRWM+OvaLNc8yawFkqnMc6dND7Vwm7ulwk7mRsSzptEeu9Ci3K/fDTpvAhOG0koghokj3K4cLvoYOvBKJFxkofX++mPESHp0QRlH620t8vgReYpRz9QjlrzFbad7gDkjcLS1DJwfaSfptQPr4t99g97+qIXMxGg9b5xpNCN6zeSPuBEkgu/MfPI4CtD9vl68R1byBrrX5RJt7yehHlV8FE/Yimlz8="
