platform:
- x86
- x64

environment:
  minio_access_key:
    secure: aOwS1IlypK95hry5rCGimEwXWuDgwlqbq6cmYYK+lnk=
  minio_secret_key:
    secure: sJ5F0ZI6+OfzZ+0NIcPpE27uhifUa5btEP2APubrKlt/Rb24eJkqhGqyXwr/Xbnk

matrix:
  fast_finish: true

init:
- git config --global core.autocrlf true

- npm install yarn --global

shallow_clone: true

install:
- ps: Install-Product node 6 $env:platform
- node -e "console.log(process.platform + '-' + process.arch)"
- node -e "console.log(require('os').platform() + '-' + require('os').arch())"
- yarn

build_script:
- ps: rm node_modules\nslog\build\Release\nslog.node
- yarn run rebuildNative

test_script:
- yarn test

deploy_script:
- node bin/deploy-appveyor.js
