platform:
- x86
- x64

environment:
  minio_access_key:
    secure: qaoKe9n5/JbUFaZ1umtftPdsP98Di4Id407+8uJBMiA=
  minio_secret_key:
    secure: H5CSqrFX61uF9/8lZwF7SZLW+pBxzUaVe32Mq/XBZwyb5c1El1SnPMizxJk6rLEO

matrix:
  fast_finish: true

init:
- git config --global core.autocrlf true

shallow_clone: true

install:
- ps: Install-Product node 6
- npm -g install npm@latest
- npm install

build_script:
- ps: rm node_modules\nslog\build\Release\nslog.node
- npm run rebuildNative

test_script:
- npm test

deploy_script:
- node bin/deploy-appveyor.js
