platform:
- x86
- x64

matrix:
  fast_finish: true

init:
- git config --global core.autocrlf true

- npm install yarn --global

shallow_clone: true

install:
- ps: Install-Product node 10 $env:platform
- node -e "console.log(process.platform + '-' + process.arch)"
- node -e "console.log(require('os').platform() + '-' + require('os').arch())"
- yarn install --frozen-lockfile

build_script:
- yarn run rebuildNative

test_script:
- yarn test

deploy_script:
- node bin/deploy-appveyor.js
